### ISSUE TITLE
regarding Participation

### ISSUE THREAD

**Issue by rohithkodali** [BarathiGanesh-HB/ARNEKT-IECSIL#1]
Hi Bharathi ganesh,

  i know i'm late to ask this question i just came to know about this competetion, i would like to participate in it but i'm not looking at any prizes or interview just wanted to participate in it, is there any way that i can get access to the data (password)

**Comment by BarathiGanesh-HB** [comment]
Please drop a mail to barathiganesh.hb@arnekt.com
