### ISSUE TITLE
Password for the zip files

### ISSUE THREAD

**Issue by napsternxg** [BarathiGanesh-HB/ARNEKT-IECSIL#2]
@BarathiGanesh-HB Some of the zip files `arnekt-iecsil-ie-corpus_test_2.zip` and `arnekt-iecsil-ie-corpus_train.zip` require a password. Can you upload the password removed zipfiles or include the password for unzipping the files?

**Comment by junaidamk** [comment]
???

**Comment by BarathiGanesh-HB** [comment]
Sorry for the delayed response: arnekt@iecsil2018
